version: '3.8'

services:

  ###############################################
  #                     Go                      #
  ###############################################

  auto-squash-go:
    build:
      context: .
      dockerfile: docker_go.Dockerfile
      args:
        - ENV=dev
    container_name: "auto_squash_go_dev"
    ports:
      - "8190"
