name: hltv-no-spoilers
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Build and publish go to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          ENV: prod
        with:
          registry: https://ghcr.io
          name: optimuscrime/hltv-no-spoilers/hltv-no-spoilers-go
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: docker_go.Dockerfile
          tags: "latest,${{ env.RELEASE_VERSION }}"
